### ISSUE TITLE
SysAdm Service Manager fails to list polkitd

### ISSUE THREAD

**Issue by mrT55** [trueos/sysadm#34]
After doing a fresh install of Trident-x64-20180831.iso (release)
pkg install policykit  (version 0.9_10)
pkg install polkit     (version 0.114_1)

sysAdm Service Manager does not include polkitd in the list of possible services.

sysadm-201806120928
sysadm-client-201802091522
trident-core-201808290904
FreeBSD-runtime-12.0.s20180831091252

**Comment by beanpole135** [comment]
That would probably be because there is no OpenRC service for polkitd.
You can verify this by looking in the /usr/local/etc/init.d directory and seeing if there is a polkitd service file.
If not, you will need to create one and submit it to the polkit port on the TrueOS ports tree: https://github.com/trueos/trueos-ports
